### ISSUE TITLE
Search doesn't work out of the box

### ISSUE THREAD

**Issue by patrickdronk** [ethanhann/eeh-navigation-demo#1]
Hi,

I've been working with this navigation for a couple of days now. And so far it's all good. But I'm now trying to fix the search, since it's not working here or on any demo. But I can't get the directive to work. If i make my own input and put ng-model="model.query" on it, it does. But then the collapse function is gone. 

Am I missing something?
And is it not a wanted thing to have the search out of the box?

Thanks in advance

**Comment by ethanhann** [comment]
Thank you for creating an issue on the main repo.
